env = "dev"
debug = true
use_login = false

[oauth]
authorization_endpoint = "https://dev-64799787.okta.com/oauth2/default/v1/authorize"
token_endpoint = "https://dev-64799787.okta.com/oauth2/default/v1/token"
jwks_uri = "https://dev-64799787.okta.com/oauth2/default/v1/keys"
redirect_uri = "http://localhost:8501"
client_id = "0oabozi565GRXkSH65d7"
client_secret = "GdeXdeMNvYL6Ey1o_XbEo0x8C0sSa4YiphDDQxe-plM0B9PwOLkXAYOR3gBsx66P"
identity_field_in_token = "sub"
audience = "api://default"
scope = "openid"
