[connections.resolver_db]
dialect = "mysql"
username = "root"
password = "root"
host = "127.0.0.1"
port = 3306
database = "resolver"

[connections.google_postbacker_db]
dialect = "mysql"
username = "root"
password = "root"
host = "127.0.0.1"
port = 3306
database = "google_postbacker"